/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cctSol from "./CCT.sol";
export type { cctSol };
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as presaleSol from "./Presale.sol";
export type { presaleSol };
import type * as saleNftSol from "./SaleNFT.sol";
export type { saleNftSol };
