/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as cctSol from "./CCT.sol";
export * as nftSol from "./NFT.sol";
export * as presaleSol from "./Presale.sol";
export * as saleNftSol from "./SaleNFT.sol";
